### ISSUE TITLE
Package:discover not working after update

### ISSUE THREAD

**Issue by josephjeno** [os-js/osjs-cli#12]
After updating to the latest version, package:discover is no longer working (on Windows 10).

The issue is traced to line 38 of [utils.js](https://github.com/os-js/osjs-cli/blob/7bb7b3d82f49eab601b64ef5c1fa5f099a90d430/src/utils.js#L38) which returns an empty array on my machine.

```
const globs = await globby(root + '/**/package.json', {deep: 3});
```

**Comment by andersevenrud** [comment]
I can confirm this issue on my windows machine.

This seems to fix the issue:

```
const globs = await globby(root.replace(/\\/g, '/') + '/**/package.json', {deep: 3});
```

**Comment by josephjeno** [comment]
Confirmed that did the trick!

**Comment by andersevenrud** [comment]
Since this does not affect non-windows systems (and I've tested just to be sure), I'm releasing a new version wit this fix now :)

**Comment by andersevenrud** [comment]
Aaaaand 3.0.21 is now out.

Thanks for reporting about this issue :heart_eyes:

**Comment by josephjeno** [comment]
Thank YOU man!
