### ISSUE TITLE
Broken links in the custom authentication adapter

### ISSUE THREAD

**Issue by mtchuenten** [os-js/osjs-cli#22]
Hello all,

I generated a new authentication adapter using `npm run make:auth` and realized that the links provided in the generated file are not accessible:
- https://manual.os-js.org/v3/tutorial/auth/
- https://manual.os-js.org/v3/guide/auth/
- https://manual.os-js.org/v3/development/

Can that be resolved please? The links are to provide more information about authentication adapters and therefore very crucial, especially for those like me who are just getting started with OS.js.

Regards.

**Comment by andersevenrud** [comment]
Thanks! I've fixed this and rolling out new release :)

**Comment by mtchuenten** [comment]
Great @andersevenrud, thanks a lot.
