### ISSUE TITLE
Directories that already exist

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-cli#6]
I think it'd be easier for people who want to make applications if the `make:application` action checked if the directory exists or not.

**Comment by andersevenrud** [comment]
It will ensure the creation of the directory, but it will not allow using existing directories.

So I think the best solution here is to add a warning that makes the user confirm to use that directory.

This would also need to make sure no files are overwritten!

Ref: https://github.com/os-js/osjs-cli/blob/master/src/tasks/scaffold.js#L147

**Comment by andersevenrud** [comment]
In the latest release of `@osjs/cli` it will now ask the following (depending on destination and answers):

1. Do you want to write to target ? **Default: yes** (this was already implemented)
2. Do you want to overwrite directory (if already exists) ? **Default: no** (new)
3. Do you want to replace files if (if they already exists in target directory) ? **Default: no** (new)

This is in `make:application` scaffolder.
