### ISSUE TITLE
sh: 1: osjs-cli: not found

### ISSUE THREAD

**Issue by SpaceboyRoss01** [os-js/osjs-cli#7]
```
$ npm run package:discover

> @osjs/osjs@3.0.0-alpha.29 package:discover /opt/os.js
> osjs-cli package:discover

sh: 1: osjs-cli: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @osjs/osjs@3.0.0-alpha.29 package:discover: `osjs-cli package:discover`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @osjs/osjs@3.0.0-alpha.29 package:discover script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osjs/.npm/_logs/2018-12-07T18_16_23_396Z-debug.log
```

**Comment by andersevenrud** [comment]
I actually answered on this issue by mail... but I guess it never got through.

This is usually a symptom of `@osjs/cli` not being installed.

`osjs-cli` is a script, provided by that package, which will get installed into `node_modules/.bin/`.

Are you still facing this issue ?

**Comment by SpaceboyRoss01** [comment]
I am not right now after installing @osjs/cli08.12.2018, 14:02, "Anders Evenrud" <notifications@github.com>:I actually answered on this issue by mail... but I guess it never got through.
This is usually a symptom of @osjs/cli not being installed.
osjs-cli is a script, provided by that package, which will get installed into node_modules/.bin/.
Are you still facing this issue ?

**Comment by andersevenrud** [comment]
If it works now, my guess is that `npm install` was not run.

Re-open this issue if the problem persists.
